// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rpcAddMsg.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Pb {
  public static partial class AddTask
  {
    static readonly string __ServiceName = "pb.AddTask";

    static readonly grpc::Marshaller<global::Pb.AddRequest> __Marshaller_pb_AddRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Pb.AddRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Pb.AddResponse> __Marshaller_pb_AddResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Pb.AddResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Pb.FileChunk> __Marshaller_pb_FileChunk = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Pb.FileChunk.Parser.ParseFrom);

    static readonly grpc::Method<global::Pb.AddRequest, global::Pb.AddResponse> __Method_AddFile = new grpc::Method<global::Pb.AddRequest, global::Pb.AddResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddFile",
        __Marshaller_pb_AddRequest,
        __Marshaller_pb_AddResponse);

    static readonly grpc::Method<global::Pb.FileChunk, global::Pb.AddResponse> __Method_TransLargeFile = new grpc::Method<global::Pb.FileChunk, global::Pb.AddResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "TransLargeFile",
        __Marshaller_pb_FileChunk,
        __Marshaller_pb_AddResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Pb.RpcAddMsgReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AddTask</summary>
    public abstract partial class AddTaskBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Pb.AddResponse> AddFile(global::Pb.AddRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Pb.AddResponse> TransLargeFile(grpc::IAsyncStreamReader<global::Pb.FileChunk> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AddTask</summary>
    public partial class AddTaskClient : grpc::ClientBase<AddTaskClient>
    {
      /// <summary>Creates a new client for AddTask</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AddTaskClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AddTask that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AddTaskClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AddTaskClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AddTaskClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Pb.AddResponse AddFile(global::Pb.AddRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddFile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Pb.AddResponse AddFile(global::Pb.AddRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddFile, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Pb.AddResponse> AddFileAsync(global::Pb.AddRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddFileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Pb.AddResponse> AddFileAsync(global::Pb.AddRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddFile, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::Pb.FileChunk, global::Pb.AddResponse> TransLargeFile(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransLargeFile(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Pb.FileChunk, global::Pb.AddResponse> TransLargeFile(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_TransLargeFile, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AddTaskClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AddTaskClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AddTaskBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddFile, serviceImpl.AddFile)
          .AddMethod(__Method_TransLargeFile, serviceImpl.TransLargeFile).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AddTaskBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddFile, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pb.AddRequest, global::Pb.AddResponse>(serviceImpl.AddFile));
      serviceBinder.AddMethod(__Method_TransLargeFile, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Pb.FileChunk, global::Pb.AddResponse>(serviceImpl.TransLargeFile));
    }

  }
}
#endregion
